services:
  - type: web
    name: real-estate-aggregator-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: node apps/api/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3003
      - key: ENABLE_WORKERS
        value: true
    healthCheckPath: /health